/**
 * Static TypeScript types for the TAKPacketV2 protobuf schema.
 *
 * Generated by hand from protobufs/meshtastic/atak.proto to match the
 * camelCase field names that protobufjs uses at runtime. Every field is
 * optional (proto3 semantics: absent == zero-value) so parsers can build
 * packets incrementally and the `stripZeros` helper can remove defaults.
 *
 * These types are intentionally compatible with `protobuf.Type.create()`,
 * `toObject()`, and the existing `Record<string, unknown>` based API so
 * migration can be done file-by-file.
 */

// ---------------------------------------------------------------------------
// Enum-like numeric constants
// ---------------------------------------------------------------------------

/** CotType enum values (field `cotTypeId`). 0 = CotType_Other. */
export type CotTypeId = number;

/** CotHow enum values (field `how`). 0 = CotHow_Unspecified. */
export type CotHow = number;

/** Team enum values (fields `team`, stroke/fill color enums). 0 = Unspecifed_Color. */
export type Team = number;

/** MemberRole enum values (field `role`). 0 = Unspecifed. */
export type MemberRole = number;

/** GeoPointSource enum values (fields `geoSrc`, `altSrc`). 0 = Unspecified. */
export type GeoPointSource = number;

// ---------------------------------------------------------------------------
// Nested message types
// ---------------------------------------------------------------------------

/** Compact geographic vertex — delta-encoded from the enclosing event's anchor. */
export interface CotGeoPoint {
  latDeltaI?: number;
  lonDeltaI?: number;
}

/** GeoChat message or receipt. */
export interface GeoChat {
  message?: string;
  to?: string;
  toCallsign?: string;
  receiptForUid?: string;
  /** 0 = None, 1 = Delivered, 2 = Read */
  receiptType?: number;
}

/** ADS-B / military air track data. */
export interface AircraftTrack {
  icao?: string;
  registration?: string;
  flight?: string;
  aircraftType?: string;
  squawk?: number;
  category?: string;
  rssiX10?: number;
  gps?: boolean;
  cotHostId?: string;
}

/** User-drawn tactical graphic (circle, rectangle, polygon, etc.). */
export interface DrawnShape {
  /** DrawnShape.Kind enum: 0=Unspecified, 1=Circle, ..., 10=Vehicle3D */
  kind?: number;
  /** DrawnShape.StyleMode: 0=Unspecified, 1=StrokeOnly, 2=FillOnly, 3=StrokeAndFill */
  style?: number;
  majorCm?: number;
  minorCm?: number;
  angleDeg?: number;
  strokeColor?: Team;
  strokeArgb?: number;
  strokeWeightX10?: number;
  fillColor?: Team;
  fillArgb?: number;
  labelsOn?: boolean;
  vertices?: CotGeoPoint[];
  truncated?: boolean;
  bullseyeDistanceDm?: number;
  bullseyeBearingRef?: number;
  bullseyeFlags?: number;
  bullseyeUidRef?: string;
}

/** Fixed point of interest: spot marker, waypoint, checkpoint, etc. */
export interface Marker {
  /** Marker.Kind enum: 0=Unspecified, 1=Spot, ..., 12=ImageMarker */
  kind?: number;
  color?: Team;
  colorArgb?: number;
  readiness?: boolean;
  parentUid?: string;
  parentType?: string;
  parentCallsign?: string;
  iconset?: string;
}

/** Range and bearing measurement line. */
export interface RangeAndBearing {
  anchor?: CotGeoPoint;
  anchorUid?: string;
  rangeCm?: number;
  bearingCdeg?: number;
  strokeColor?: Team;
  strokeArgb?: number;
  strokeWeightX10?: number;
}

/** Route waypoint/control point link. */
export interface RouteLink {
  point?: CotGeoPoint;
  uid?: string;
  callsign?: string;
  linkType?: number;
}

/** Named route with ordered waypoints and control points. */
export interface Route {
  /** Route.Method: 0=Unspecified, 1=Driving, ..., 5=Watercraft */
  method?: number;
  /** Route.Direction: 0=Unspecified, 1=Infil, 2=Exfil */
  direction?: number;
  prefix?: string;
  strokeWeightX10?: number;
  links?: RouteLink[];
  truncated?: boolean;
}

/** Per-patient ZMIST clinical record. */
export interface ZMistEntry {
  title?: string;
  z?: string;
  m?: string;
  i?: string;
  s?: string;
  t?: string;
}

/** 9-line MEDEVAC/CASEVAC request (b-r-f-h-c). */
export interface CasevacReport {
  /** CasevacReport.Precedence: 0=Unspecified, 1=Urgent, ..., 5=Convenience */
  precedence?: number;
  equipmentFlags?: number;
  litterPatients?: number;
  ambulatoryPatients?: number;
  /** CasevacReport.Security: 0=Unspecified, 1=NoEnemy, ..., 4=EnemyInArmedContact */
  security?: number;
  /** CasevacReport.HlzMarking: 0=Unspecified, 1=Panels, ..., 5=Other */
  hlzMarking?: number;
  zoneMarker?: string;
  usMilitary?: number;
  usCivilian?: number;
  nonUsMilitary?: number;
  nonUsCivilian?: number;
  epw?: number;
  child?: number;
  terrainFlags?: number;
  frequency?: string;
  // v2.x medline extensions
  title?: string;
  medlineRemarks?: string;
  urgentCount?: number;
  urgentSurgicalCount?: number;
  priorityCount?: number;
  routineCount?: number;
  convenienceCount?: number;
  equipmentDetail?: string;
  zoneProtectedCoord?: string;
  terrainSlopeDir?: string;
  terrainOtherDetail?: string;
  markedBy?: string;
  obstacles?: string;
  windsAreFrom?: string;
  friendlies?: string;
  enemy?: string;
  hlzRemarks?: string;
  zmist?: ZMistEntry[];
}

/** Emergency alert / 911 beacon. */
export interface EmergencyAlert {
  /** EmergencyAlert.Type: 0=Unspecified, 1=Alert911, ..., 6=Cancel */
  type?: number;
  authoringUid?: string;
  cancelReferenceUid?: string;
}

/** Task / engage request (t-s). */
export interface TaskRequest {
  taskType?: string;
  targetUid?: string;
  assigneeUid?: string;
  /** TaskRequest.Priority: 0=Unspecified, 1=Low, ..., 4=Critical */
  priority?: number;
  /** TaskRequest.Status: 0=Unspecified, 1=Pending, ..., 5=Cancelled */
  status?: number;
  note?: string;
}

/** Weather annotation from <environment> detail element. */
export interface TAKEnvironment {
  temperatureCX10?: number;
  windDirectionDeg?: number;
  windSpeedCmS?: number;
}

/** Sensor field-of-view cone. */
export interface SensorFov {
  /** SensorFov.SensorType: 0=Unspecified, 1=Camera, ..., 6=Other */
  type?: number;
  azimuthDeg?: number;
  rangeM?: number;
  fovHorizontalDeg?: number;
  fovVerticalDeg?: number;
  elevationDeg?: number;
  rollDeg?: number;
  model?: string;
}

// ---------------------------------------------------------------------------
// Top-level TAKPacketV2
// ---------------------------------------------------------------------------

/**
 * TAKPacketV2 — the top-level protobuf message for ATAK v2 packets.
 *
 * All fields are optional per proto3 semantics. The `payload_variant` oneof
 * is represented as optional fields — exactly one should be set at a time.
 *
 * This interface is structurally compatible with `protobuf.Type.create()` and
 * `protobuf.Type.toObject()` so it can be used interchangeably with the
 * runtime reflection API.
 */
export interface TAKPacketV2 {
  // --- Common envelope fields ---
  cotTypeId?: CotTypeId;
  how?: CotHow;
  callsign?: string;
  team?: Team;
  role?: MemberRole;
  latitudeI?: number;
  longitudeI?: number;
  altitude?: number;
  speed?: number;
  course?: number;
  battery?: number;
  geoSrc?: GeoPointSource;
  altSrc?: GeoPointSource;
  uid?: string;
  deviceCallsign?: string;
  staleSeconds?: number;
  takVersion?: string;
  takDevice?: string;
  takPlatform?: string;
  takOs?: string;
  endpoint?: string;
  phone?: string;
  cotTypeStr?: string;
  remarks?: string;

  // --- Optional annotations ---
  environment?: TAKEnvironment;
  sensorFov?: SensorFov;

  // --- payload_variant oneof (exactly one should be set) ---
  pli?: boolean;
  chat?: GeoChat;
  aircraft?: AircraftTrack;
  rawDetail?: Uint8Array | Buffer;
  shape?: DrawnShape;
  marker?: Marker;
  rab?: RangeAndBearing;
  route?: Route;
  casevac?: CasevacReport;
  emergency?: EmergencyAlert;
  task?: TaskRequest;
}
