/**
 * Static TypeScript types for the TAKPacketV2 protobuf schema.
 *
 * Generated by hand from protobufs/meshtastic/atak.proto to match the
 * camelCase field names that protobufjs uses at runtime. Every field is
 * optional (proto3 semantics: absent == zero-value) so parsers can build
 * packets incrementally and the `stripZeros` helper can remove defaults.
 *
 * These types are intentionally compatible with `protobuf.Type.create()`,
 * `toObject()`, and the existing `Record<string, unknown>` based API so
 * migration can be done file-by-file.
 */

// ---------------------------------------------------------------------------
// Enum-like numeric constants
// ---------------------------------------------------------------------------

/** CotType enum values (field `cotTypeId`). 0 = CotType_Other. */
export type CotTypeId = number;

/** CotHow enum values (field `how`). 0 = CotHow_Unspecified. */
export type CotHow = number;

/** Team enum values (fields `team`, stroke/fill color enums). 0 = Unspecifed_Color. */
export type Team = number;

/** MemberRole enum values (field `role`). 0 = Unspecifed. */
export type MemberRole = number;

/** GeoPointSource enum values (fields `geoSrc`, `altSrc`). 0 = Unspecified. */
export type GeoPointSource = number;

// ---------------------------------------------------------------------------
// Nested message types
// ---------------------------------------------------------------------------

/** Compact geographic vertex — delta-encoded from the enclosing event's anchor. */
export interface CotGeoPoint {
  latDeltaI?: number;
  lonDeltaI?: number;
}

/** GeoChat message or receipt. */
export interface GeoChat {
  message?: string;
  to?: string;
  toCallsign?: string;
  receiptForUid?: string;
  /** 0 = None, 1 = Delivered, 2 = Read */
  receiptType?: number;
  // --- TAKTALK-flavored b-t-f extensions ---
  /** TAKTALK language tag from <Ea> (e.g. "English"). Absent on non-TAKTALK chats. */
  lang?: string;
  /** TAKTALK room UUID from <roomId>. Absent on non-TAKTALK chats. */
  roomId?: string;
  /**
   * TAKTALK voice profile pointer from <voice_profile_id>. Often empty
   * even when present — the empty marker is still a TAKTALK origination
   * signal. Use "field is defined at all" to distinguish from "absent".
   */
  voiceProfileId?: string;
}

/** TAKTALK voice/text chat message (CoT type m-t-t). */
export interface TakTalkMessage {
  text?: string;
  chatroomId?: string;
  lang?: string;
  /** True when the source CoT carried a <voice/> push-to-talk marker. */
  fromVoice?: boolean;
}

/** TAKTALK room/membership broadcast (CoT type y-). */
export interface TakTalkRoomData {
  /**
   * DEPRECATED in v0.3.2 — always equals envelope TAKPacketV2.callsign in
   * valid packets, so the duplicate wire byte was redundant. Builders stop
   * writing this field; parsers still read it for one release so v0.3.1-
   * encoded packets decode cleanly. To be removed entirely in v0.4.x.
   */
  senderCallsign?: string;
  roomId?: string;
  roomName?: string;
  participants?: string[];
}

/**
 * ATAK directed-routing recipient list (CoT <marti><dest callsign='X'/>…</marti>).
 *
 * Present when an event is addressed to specific TAK users rather than the
 * broadcast group. TAKTALK gates voice TTS on this element matching the
 * receiver's callsign; directed b-t-f chats use it the same way. A missing
 * Marti means "broadcast to all peers" (the default for PLI / situational-
 * awareness events).
 */
export interface Marti {
  destCallsign?: string[];
}

/** ADS-B / military air track data. */
export interface AircraftTrack {
  icao?: string;
  registration?: string;
  flight?: string;
  aircraftType?: string;
  squawk?: number;
  category?: string;
  rssiX10?: number;
  gps?: boolean;
  cotHostId?: string;
}

/** User-drawn tactical graphic (circle, rectangle, polygon, etc.). */
export interface DrawnShape {
  /** DrawnShape.Kind enum: 0=Unspecified, 1=Circle, ..., 10=Vehicle3D */
  kind?: number;
  /** DrawnShape.StyleMode: 0=Unspecified, 1=StrokeOnly, 2=FillOnly, 3=StrokeAndFill */
  style?: number;
  majorCm?: number;
  minorCm?: number;
  angleDeg?: number;
  strokeColor?: Team;
  strokeArgb?: number;
  strokeWeightX10?: number;
  fillColor?: Team;
  fillArgb?: number;
  labelsOn?: boolean;
  /**
   * Vertex deltas as two PACKED parallel columns (lat, lon) of signed 1e-7°
   * deltas from the event anchor. vertex N is (vertexLatDeltas[N],
   * vertexLonDeltas[N]); the columns are the same length. Packed encoding pays
   * the field framing once per column instead of once per vertex. See atak.proto.
   */
  vertexLatDeltas?: number[];
  vertexLonDeltas?: number[];
  truncated?: boolean;
  bullseyeDistanceDm?: number;
  bullseyeBearingRef?: number;
  bullseyeFlags?: number;
  bullseyeUidRef?: string;
}

/** Fixed point of interest: spot marker, waypoint, checkpoint, etc. */
export interface Marker {
  /** Marker.Kind enum: 0=Unspecified, 1=Spot, ..., 12=ImageMarker */
  kind?: number;
  color?: Team;
  colorArgb?: number;
  readiness?: boolean;
  parentUid?: string;
  parentType?: string;
  parentCallsign?: string;
  iconset?: string;
}

/** Range and bearing measurement line. */
export interface RangeAndBearing {
  anchor?: CotGeoPoint;
  anchorUid?: string;
  rangeCm?: number;
  bearingCdeg?: number;
  strokeColor?: Team;
  strokeArgb?: number;
  strokeWeightX10?: number;
}

/** Route waypoint/control point link. */
export interface RouteLink {
  point?: CotGeoPoint;
  uid?: string;
  callsign?: string;
  linkType?: number;
}

/** Named route with ordered waypoints and control points. */
export interface Route {
  /** Route.Method: 0=Unspecified, 1=Driving, ..., 5=Watercraft */
  method?: number;
  /** Route.Direction: 0=Unspecified, 1=Infil, 2=Exfil */
  direction?: number;
  prefix?: string;
  strokeWeightX10?: number;
  links?: RouteLink[];
  truncated?: boolean;
}

/** Per-patient ZMIST clinical record. */
export interface ZMistEntry {
  title?: string;
  z?: string;
  m?: string;
  i?: string;
  s?: string;
  t?: string;
}

/** 9-line MEDEVAC/CASEVAC request (b-r-f-h-c). */
export interface CasevacReport {
  /** CasevacReport.Precedence: 0=Unspecified, 1=Urgent, ..., 5=Convenience */
  precedence?: number;
  equipmentFlags?: number;
  litterPatients?: number;
  ambulatoryPatients?: number;
  /** CasevacReport.Security: 0=Unspecified, 1=NoEnemy, ..., 4=EnemyInArmedContact */
  security?: number;
  /** CasevacReport.HlzMarking: 0=Unspecified, 1=Panels, ..., 5=Other */
  hlzMarking?: number;
  zoneMarker?: string;
  usMilitary?: number;
  usCivilian?: number;
  nonUsMilitary?: number;
  nonUsCivilian?: number;
  epw?: number;
  child?: number;
  terrainFlags?: number;
  frequency?: string;
  // v2.x medline extensions
  title?: string;
  medlineRemarks?: string;
  urgentCount?: number;
  urgentSurgicalCount?: number;
  priorityCount?: number;
  routineCount?: number;
  convenienceCount?: number;
  equipmentDetail?: string;
  zoneProtectedCoord?: string;
  terrainSlopeDir?: string;
  terrainOtherDetail?: string;
  markedBy?: string;
  obstacles?: string;
  windsAreFrom?: string;
  friendlies?: string;
  enemy?: string;
  hlzRemarks?: string;
  zmist?: ZMistEntry[];
}

/** Emergency alert / 911 beacon. */
export interface EmergencyAlert {
  /** EmergencyAlert.Type: 0=Unspecified, 1=Alert911, ..., 6=Cancel */
  type?: number;
  authoringUid?: string;
  cancelReferenceUid?: string;
}

/** Task / engage request (t-s). */
export interface TaskRequest {
  taskType?: string;
  targetUid?: string;
  assigneeUid?: string;
  /** TaskRequest.Priority: 0=Unspecified, 1=Low, ..., 4=Critical */
  priority?: number;
  /** TaskRequest.Status: 0=Unspecified, 1=Pending, ..., 5=Cancelled */
  status?: number;
  note?: string;
}

/** Weather annotation from <environment> detail element. */
export interface TAKEnvironment {
  temperatureCX10?: number;
  windDirectionDeg?: number;
  windSpeedCmS?: number;
}

/** Sensor field-of-view cone. */
export interface SensorFov {
  /** SensorFov.SensorType: 0=Unspecified, 1=Camera, ..., 6=Other */
  type?: number;
  azimuthDeg?: number;
  rangeM?: number;
  fovHorizontalDeg?: number;
  fovVerticalDeg?: number;
  elevationDeg?: number;
  rollDeg?: number;
  model?: string;
}

// ---------------------------------------------------------------------------
// Top-level TAKPacketV2
// ---------------------------------------------------------------------------

/**
 * TAKPacketV2 — the top-level protobuf message for ATAK v2 packets.
 *
 * All fields are optional per proto3 semantics. The `payload_variant` oneof
 * is represented as optional fields — exactly one should be set at a time.
 *
 * This interface is structurally compatible with `protobuf.Type.create()` and
 * `protobuf.Type.toObject()` so it can be used interchangeably with the
 * runtime reflection API.
 */
export interface TAKPacketV2 {
  // --- Common envelope fields ---
  cotTypeId?: CotTypeId;
  how?: CotHow;
  callsign?: string;
  team?: Team;
  role?: MemberRole;
  latitudeI?: number;
  longitudeI?: number;
  altitude?: number;
  speed?: number;
  course?: number;
  battery?: number;
  geoSrc?: GeoPointSource;
  altSrc?: GeoPointSource;
  uid?: string;
  deviceCallsign?: string;
  staleSeconds?: number;
  takVersion?: string;
  takDevice?: string;
  takPlatform?: string;
  takOs?: string;
  endpoint?: string;
  phone?: string;
  cotTypeStr?: string;
  remarks?: string;

  // --- Optional annotations ---
  environment?: TAKEnvironment;
  sensorFov?: SensorFov;
  /**
   * Directed-routing recipient list (CoT <marti><dest callsign='X'/>…</marti>).
   * Absent / undefined = broadcast (default for situational-awareness);
   * populated for TAKTALK m-t-t and directed b-t-f DMs. TAKTALK gates voice
   * TTS playback on this list matching the receiver's callsign, so dropping
   * it silently breaks voice messaging end-to-end.
   */
  marti?: Marti;

  // --- payload_variant oneof (at most one set; PLI is implicit = none set) ---
  // Tag 30 (former `bool pli`) was dropped in v0.4.0 — a position report sets
  // no payload variant. See atak.proto.
  chat?: GeoChat;
  aircraft?: AircraftTrack;
  rawDetail?: Uint8Array | Buffer;
  shape?: DrawnShape;
  marker?: Marker;
  rab?: RangeAndBearing;
  route?: Route;
  casevac?: CasevacReport;
  emergency?: EmergencyAlert;
  task?: TaskRequest;
  taktalk?: TakTalkMessage;
  taktalkRoom?: TakTalkRoomData;
}
