using Meshtastic.TAK;

namespace Meshtastic.TAK.Tests;

/// <summary>
/// Validates the C# <see cref="CotMeshSanitizer"/> against the cross-binding
/// golden fixtures generated by the canonical Kotlin test. The Kotlin golden
/// under <c>testdata/sanitizer/</c> is the source of truth: if these fail, fix
/// the C# regex to match Kotlin — never edit the golden.
/// </summary>
public class CotMeshSanitizerTests
{
    private static readonly string TestDataDir = Path.GetFullPath(
        Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "..", "..", "testdata"));

    private static string Load(string name) =>
        File.ReadAllText(Path.Combine(TestDataDir, "sanitizer", name));

    [Fact]
    public void Strip_MatchesGolden()
    {
        var input = Load("strip.in.xml");
        var expected = Load("strip.out.xml");
        Assert.Equal(expected.TrimEnd(), CotMeshSanitizer.StripNonEssentialForMesh(input).TrimEnd());
    }

    [Fact]
    public void Normalize_MatchesGolden()
    {
        var input = Load("normalize.in.xml");
        var expected = Load("normalize.out.xml");
        Assert.Equal(expected.TrimEnd(), CotMeshSanitizer.NormalizeCotXml(input).TrimEnd());
    }

    [Fact]
    public void Strip_PreservesTakTalkAndStripsDisplayOnly()
    {
        var output = CotMeshSanitizer.StripNonEssentialForMesh(Load("strip.in.xml"));
        // TAK-Talk essentials must survive.
        Assert.Contains("<voice/>", output);
        Assert.Contains("dest callsign=\"ETHEL\"", output);
        // Display-only element and route-link uid must be gone.
        Assert.DoesNotContain("<takv", output);
        Assert.DoesNotContain("uid=\"LINK-UUID", output);
    }
}
