import XCTest
@testable import MeshtasticTAK

/// Golden-fixture parity tests for `CotMeshSanitizer`.
///
/// Deliberately uses **XCTest** (not the Swift `Testing` framework) so it
/// builds and runs in environments where the `Testing` module is unavailable,
/// while still being picked up by Apple CI.
///
/// The fixtures under `testdata/sanitizer/` are generated by the canonical
/// Kotlin `CotMeshSanitizerTest` and are the source of truth — every binding
/// must reproduce them byte-for-byte (after trimming surrounding whitespace,
/// which the fixture files carry as a trailing newline).
final class CotMeshSanitizerTests: XCTestCase {

    private static let sanitizerDir = TestFixtures.testDataDir
        .appendingPathComponent("sanitizer")

    private func loadFixture(_ name: String) throws -> String {
        let url = Self.sanitizerDir.appendingPathComponent(name)
        return try String(contentsOf: url, encoding: .utf8)
    }

    func testStripNonEssentialForMeshMatchesGolden() throws {
        let input = try loadFixture("strip.in.xml")
        let expected = try loadFixture("strip.out.xml")
        let actual = CotMeshSanitizer.stripNonEssentialForMesh(input)
        XCTAssertEqual(
            actual.trimmingCharacters(in: .whitespacesAndNewlines),
            expected.trimmingCharacters(in: .whitespacesAndNewlines)
        )
    }

    func testNormalizeCotXmlMatchesGolden() throws {
        let input = try loadFixture("normalize.in.xml")
        let expected = try loadFixture("normalize.out.xml")
        let actual = CotMeshSanitizer.normalizeCotXml(input)
        XCTAssertEqual(
            actual.trimmingCharacters(in: .whitespacesAndNewlines),
            expected.trimmingCharacters(in: .whitespacesAndNewlines)
        )
    }

    /// Spot-checks that the strip transform preserves TAK-Talk essentials
    /// (`<voice>`, `<marti><dest …>`) while removing display-only elements
    /// (`<takv>`) and route-waypoint `<link>` UUIDs.
    func testStripPreservesTakTalkAndDropsOverhead() throws {
        let input = try loadFixture("strip.in.xml")
        let actual = CotMeshSanitizer.stripNonEssentialForMesh(input)

        // Preserved TAK-Talk essentials.
        XCTAssertTrue(actual.contains("<voice/>"), "voice must be preserved")
        XCTAssertTrue(
            actual.contains("dest callsign=\"ETHEL\""),
            "marti dest callsign must be preserved"
        )

        // Removed overhead.
        XCTAssertFalse(actual.contains("<takv"), "takv must be stripped")
        XCTAssertFalse(
            actual.contains("uid=\"LINK-UUID"),
            "route-link uid must be stripped"
        )
    }
}
