import Foundation

/// Shared test-fixture helper for the Swift test suite.
///
/// Fixtures are loaded directly from the shared `testdata/` directory at the
/// repository root using a path built from `#filePath`. This matches the
/// Kotlin, Python, C#, and TypeScript test suites which all read from the
/// same directory, so any new fixture added via Kotlin's `CompressionTest`
/// (the canonical generator) is automatically visible to every platform.
///
/// Previously Swift maintained its own duplicate `Fixtures/` directory under
/// `swift/Tests/MeshtasticTAKTests/Fixtures/` that Swift Package Manager
/// copied into the test bundle via `.copy("Fixtures")`. That scheme went
/// stale any time the Kotlin golden regenerator produced new `.pb` / `.bin`
/// bytes and required a manual copy. Loading from the repo root eliminates
/// that drift.
enum TestFixtures {

    /// Absolute URL of the repo-root `testdata/` directory, resolved from
    /// this Swift source file's location at compile time.
    static let testDataDir: URL = {
        // `#filePath` = .../swift/Tests/MeshtasticTAKTests/TestFixtures.swift
        // → up 4 levels → repo root → `testdata/`
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // MeshtasticTAKTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // swift
            .deletingLastPathComponent()  // repo root
            .appendingPathComponent("testdata")
    }()

    static let cotXmlDir: URL = testDataDir.appendingPathComponent("cot_xml")
    static let goldenDir: URL = testDataDir.appendingPathComponent("golden")
    static let protobufDir: URL = testDataDir.appendingPathComponent("protobuf")
    static let malformedDir: URL = testDataDir.appendingPathComponent("malformed")

    /// Every fixture base name (without the `.xml` suffix), sorted for
    /// stable test ordering. Computed once and cached.
    static let fixtureNames: [String] = {
        let files = (try? FileManager.default.contentsOfDirectory(atPath: cotXmlDir.path)) ?? []
        return files
            .filter { $0.hasSuffix(".xml") }
            .map { String($0.dropLast(4)) }
            .sorted()
    }()

    /// Load the XML text for a fixture by base name (e.g. `"pli_basic"`).
    static func loadFixture(_ name: String) throws -> String {
        let url = cotXmlDir.appendingPathComponent("\(name).xml")
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Load the expected golden compressed wire payload by base name, or nil
    /// if the file is missing (golden files are regenerated by the Kotlin
    /// CompressionTest and may temporarily lag behind the XML fixtures).
    static func loadGolden(_ name: String) -> Data? {
        let url = goldenDir.appendingPathComponent("\(name).bin")
        return try? Data(contentsOf: url)
    }

    /// Load the expected protobuf bytes by base name, or nil if missing.
    static func loadProtobuf(_ name: String) -> Data? {
        let url = protobufDir.appendingPathComponent("\(name).pb")
        return try? Data(contentsOf: url)
    }

    /// Load a malformed-input fixture by filename, e.g. `"invalid_dict_id.bin"`.
    static func loadMalformed(_ name: String) throws -> Data {
        let url = malformedDir.appendingPathComponent(name)
        return try Data(contentsOf: url)
    }

    /// Load a malformed-input XML fixture as text.
    static func loadMalformedXml(_ name: String) throws -> String {
        let url = malformedDir.appendingPathComponent(name)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
